# GROUP BY
SELECT COUNTRYCODE, MAX(POPULATION) AS 'MAX' # AVG,MIN,COUNT,COUNT(DISTINCT), STDEV, VARIANCE
FROM CITY
GROUP BY COUNTRYCODE;

#Q. 도시는 몇 개인가? 도시들의 평균 인구수는?
SELECT COUNT(*)
FROM CITY;

SELECT COUNTRYCODE, AVG(POPULATION)
FROM CITY
GROUP BY COUNTRYCODE;

#HAVING -반드시 GROUP BY 다음에 와야함, 집계함수에 대해서 조건제한하는 것
SELECT COUNTRYCODE, MAX(POPULATION)
FROM CITY
GROUP BY COUNTRYCODE
HAVING MAX(POPULATION) > 8000000;

#ROLLUP - 총합, 중간합계가 필요할 경우 사용, GROUP BY절과 함께 사용
SELECT COUNTRYCODE, NAME, SUM(POPULATION)
FROM CITY
GROUP BY COUNTRYCODE, NAME WITH ROLLUP;
