# MYSQL 내장함수
SELECT LENGTH('1234');

#CONCAT-전달받은 문자열 모두 결합, 하나라도 NULL이면 NULL반환
SELECT CONCAT('MY','SQL OP','EN SOURCE');

#LOCATE-문자열 내에서 찾는 문자열이 처음으로 나타나는 위치 반환, 없으면 0
SELECT LOCATE('ABC', 'ABABCABABABABABABAABDABDABC');

#LEFT, RIGHT
SELECT LEFT('MYSQL IS AN OPEN SOURCE',5);
SELECT RIGHT('MYSQL IS AN OPEN SOURCE',5);

#LOWER, UPPER

#REPLACE
SELECT REPLACE('MSSQL', 'MS','MY');

#TRIM
SELECT TRIM('             MYSQL            '),
TRIM(LEADING '#' FROM '###MYSQL###'),
TRIM(TRAILING '#' FROM '###MYSQL###');

#FORMAT-세자리마다 ,해주는 거(문자열로 바뀜), 두번째 인수는 반올림할 소수 부분의 자릿수
SELECT FORMAT(123456789.123456,3);

#FLOOR, CEIL, ROUND

#SQRT(양의 제곱근), POW, EXP, LOG
SELECT SQRT(4),POW(2,3),EXP(3),LOG(3);

#SIN,COS,TAN

#ABS, RAND-0이상 1미만의 하나의 실수 무작위로 생성
SELECT RAND(), ROUND(RAND()*100, 0);

#!!!중요!!!날짜
#1. NOW, CURDATE,CURTIME
SELECT NOW(), CURDATE(), CURTIME();

#2. DATE, MONTH, DAY, HOUR, MINUTE, SECOND
SELECT NOW(), DATE(NOW()), MONTH(NOW()),HOUR(NOW()), MINUTE(NOW()), SECOND(NOW());

#3. MONTHNAME, DAYNAME
SELECT NOW(), MONTHNAME(NOW()), DAYNAME(NOW());

#4. DAYOFWEEK(일=1, 토=7), DAYOFMONTH, DAYOFYEAR
SELECT NOW(), DAYOFWEEK(NOW()), DAYOFMONTH(NOW()), DAYOFYEAR(NOW());

#5. DATE_FORMAT
SELECT NOW(), DATE_FORMAT(NOW(), '%D %y %a %d %m %n %j');





